# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f296a8e810e743d8dca695d0f50f23fc731ff32d52160c8ec819e4ccdc4665d0b54fd2f42c121ef1ae4df21ead55f95bfaecd91082a1f885c26140d679b47845

test:
  secret_key_base: b5f18a746de9905407c0ad9cbeb88482879a5805ee806a3f72a1af0a6e9a4e19698e9a6da65c32ebfd5656e99292d1e2ba1d42cc53242ede5e7a1df95e10f3a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
